spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/clusus_boobmerg?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root 
    password: deadhead